timeout: 3600s
substitutions:
  _LOCATION: US
  _PROJECT_REGION: us-central1
  _TFSEC_VERSION: 1.28.4
options:
  logging: CLOUD_LOGGING_ONLY
steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  secretEnv:
  - DOPPLER_TOKEN
  args:
  - -c
  - echo "Doppler Setup..." && curl -Ls https://cli.doppler.com/install.sh | sh && doppler secrets download --project stack-analyzer --config v1 --no-file --format docker > /workspace/.env
  id: setup-doppler
- id: Build
  name: hashicorp/terraform:latest
  entrypoint: sh
  args:
  - -c
  - 'if [ -f /workspace/.env ]; then . /workspace/.env; fi

    export PROJECT_ID="${PROJECT_ID}" && \

    export BUILD_ID="${BUILD_ID}" && \

    export LOCATION="${_LOCATION}" && \

    export PROJECT_REGION="${_PROJECT_REGION}" && \

    export TRIGGER_NAME="${TRIGGER_NAME}" && \

    export COMMIT_SHA="${COMMIT_SHA}" && \

    export REVISION_ID="${REVISION_ID}" && \

    export SHORT_SHA="${SHORT_SHA}" && \

    export REPO_NAME="${REPO_NAME}" && \

    export BRANCH_NAME="${BRANCH_NAME}" && \

    export TAG_NAME="${TAG_NAME}" && \

    export REF_NAME="${REF_NAME}" && \

    export TRIGGER_BUILD_CONFIG_PATH="${TRIGGER_BUILD_CONFIG_PATH}" && \

    apk --no-cache add gettext && \

    echo "$(cat parameters/${BRANCH_NAME}.tfvars | envsubst)" > parameters/${BRANCH_NAME}.tfvars && \

    echo "$(cat parameters/${BRANCH_NAME}.tfbackend | envsubst)" > parameters/${BRANCH_NAME}.tfbackend && \

    wget https://github.com/tfsec/tfsec/releases/download/v${_TFSEC_VERSION}/tfsec-linux-amd64 -O tfsec && \

    chmod +x tfsec && mv tfsec /usr/local/bin/ && \

    tfsec --no-color && \

    terraform init -backend-config="./parameters/${BRANCH_NAME}.tfbackend" && \

    terraform plan -var-file "./parameters/${BRANCH_NAME}.tfvars"

    '
- id: Deploy
  name: hashicorp/terraform:latest
  entrypoint: sh
  args:
  - -c
  - 'if [ -f /workspace/.env ]; then . /workspace/.env; fi

    export PROJECT_ID="${PROJECT_ID}" && \

    export BUILD_ID="${BUILD_ID}" && \

    export LOCATION="${_LOCATION}" && \

    export PROJECT_REGION="${_PROJECT_REGION}" && \

    export TRIGGER_NAME="${TRIGGER_NAME}" && \

    export COMMIT_SHA="${COMMIT_SHA}" && \

    export REVISION_ID="${REVISION_ID}" && \

    export SHORT_SHA="${SHORT_SHA}" && \

    export REPO_NAME="${REPO_NAME}" && \

    export BRANCH_NAME="${BRANCH_NAME}" && \

    export TAG_NAME="${TAG_NAME}" && \

    export REF_NAME="${REF_NAME}" && \

    export TRIGGER_BUILD_CONFIG_PATH="${TRIGGER_BUILD_CONFIG_PATH}" && \

    apk --no-cache add gettext && \

    echo "$(cat parameters/${BRANCH_NAME}.tfvars | envsubst)" > parameters/${BRANCH_NAME}.tfvars && \

    echo "$(cat parameters/${BRANCH_NAME}.tfbackend | envsubst)" > parameters/${BRANCH_NAME}.tfbackend && \

    terraform init -backend-config="./parameters/${BRANCH_NAME}.tfbackend" && \

    terraform apply -var-file "./parameters/${BRANCH_NAME}.tfvars" -auto-approve && \

    terraform output -json > _OUTPUT

    '
availableSecrets:
  secretManager:
  - versionName: projects/common-486006/secrets/doppler-token/versions/latest
    env: DOPPLER_TOKEN
